### ISSUE TITLE
프로젝트 세팅

### ISSUE THREAD

**Issue by easyxxu** [easyxxu/moa#1]
# 🛠️ 제목
## Todo
- [x] Font Global 적용
- [x] Color Global Style 설정
- [x] 아이콘, 이미지 저장
- [x] 안쓰는 Default 파일 삭제
